"""add_pump_model

Revision ID: 01267d45f805
Revises: 8d03f6aa1ef7
Create Date: 2022-11-14 21:19:34.853564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01267d45f805'
down_revision = '8d03f6aa1ef7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PumpAggregate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station', sa.Integer(), nullable=False),
    sa.Column('ost_id', sa.Integer(), nullable=True),
    sa.Column('pump', sa.String(), nullable=True),
    sa.Column('electric_motor', sa.String(), nullable=False),
    sa.Column('kpd_pump', sa.Float(), nullable=False),
    sa.Column('kpd_electric', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ost_id'], ['OST.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PumpAggregate')
    # ### end Alembic commands ###
