"""first

Revision ID: 8d03f6aa1ef7
Revises: 
Create Date: 2022-11-13 14:10:50.965041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d03f6aa1ef7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OST',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neft_upr', sa.String(), nullable=False),
    sa.Column('ost', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('ost_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ost_id'], ['OST.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('OST')
    # ### end Alembic commands ###
